name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rust Release binary
      uses: rust-build/rust-build.action@v1.0.3
      with:
        RUSTTARGET: x86_64-pc-windows-gnu
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

